# Template for Hugging Face token Kubernetes secret
# Replace YOUR_HUGGINGFACE_TOKEN_HERE with your actual token before applying
# Apply with: kubectl apply -f huggingface-token-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: huggingface-token
type: Opaque
stringData:
  HF_TOKEN: "YOUR_HUGGINGFACE_TOKEN"
