apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2026-02-11T22:10:01Z"
  generation: 2
  labels:
    app.kubernetes.io/name: kserve-controller-manager
    app.kubernetes.io/part-of: kserve
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: "1.0"
  name: kserve-controller-manager
  namespace: opendatahub
  resourceVersion: "1770864555893791004"
  uid: 309702f8-89ef-4e88-9c2d-7bd4b87f781a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/part-of: kserve
      control-plane: kserve-controller-manager
      controller-tools.k8s.io: "1.0"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        kubectl.kubernetes.io/restartedAt: "2026-02-11T20:48:29-06:00"
      labels:
        app.kubernetes.io/name: kserve-controller-manager
        app.kubernetes.io/part-of: kserve
        control-plane: kserve-controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        env:
        - name: SERVICE_CA_SIGNING_SECRET_NAME
          value: opendatahub-ca
        - name: SERVICE_CA_SIGNING_SECRET_NAMESPACE
          value: cert-manager
        - name: ISTIO_CA_CERTIFICATE_PATH
          value: /var/run/secrets/opendatahub/ca.crt
        - name: ENABLE_ISVC_CONTROLLER
          value: "false"
        - name: ENABLE_LLMISVC_CONTROLLER
          value: "true"
        - name: ENABLE_TRAINED_MODEL_CONTROLLER
          value: "false"
        - name: ENABLE_INFERENCE_GRAPH_CONTROLLER
          value: "false"
        - name: LLMISVC_AUTH_DISABLED
          value: "true"
        - name: LLMISVC_MONITORING_DISABLED
          value: "true"
        - name: LLMISVC_SCC_DISABLED
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SECRET_NAME
          value: kserve-webhook-server-cert
        image: quay.io/opendatahub/kserve-controller:v0.15-latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: kserve-controller-manager
      serviceAccountName: kserve-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: kserve-webhook-server-cert
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-02-11T22:10:43Z"
    lastUpdateTime: "2026-02-11T22:10:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-02-11T22:10:02Z"
    lastUpdateTime: "2026-02-12T02:49:15Z"
    message: ReplicaSet "kserve-controller-manager-5755984698" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
